---
include:
  - board: ergohaven
    shield: imperial44_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: ergohaven
    shield: imperial44_right
  - board: ergohaven
    shield: imperial44_qube qube dongle_screen
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: imperial44_qube-ergohaven-zmk
  - board: ergohaven
    shield: imperial44_left_qube
  - board: ergohaven
    shield: trackball
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: ergohaven
    shield: settings_reset
